# Generated by Django 6.1 on 2026-09-04 03:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150, unique=True)),
                ('item_group', models.CharField(blank=True, max_length=100)),
                ('conversion', models.DecimalField(decimal_places=4, default=1, help_text='1 main unit = conversion alt units', max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opening_main', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opening_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('print_name', models.CharField(blank=True, max_length=50)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('primary_group', models.BooleanField(default=True)),
                ('nature', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('EQUITY', 'Equity')], default='ASSET', max_length=12)),
                ('under_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_groups', to='masters.accountgroup')),
            ],
            options={
                'verbose_name': 'Account Group',
                'verbose_name_plural': 'Account Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=150, unique=True)),
                ('opening', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opening_type', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], default='DR', max_length=2)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('gst', models.CharField(blank=True, max_length=20)),
                ('mobile_no', models.CharField(blank=True, max_length=20)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='masters.accountgroup')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['account_name'],
            },
        ),
        migrations.CreateModel(
            name='BillSundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('ADDITIVE', 'Additive'), ('SUBTRACTIVE', 'Subtractive')], max_length=12)),
                ('amount_of', models.CharField(choices=[('PERCENT', 'Percentage'), ('ABSOLUTE', 'Absolute amount')], default='PERCENT', max_length=10)),
                ('default_value', models.DecimalField(decimal_places=4, default=0, help_text='Percentage or default amount, depending on Amount Of.', max_digits=15)),
                ('apply_on', models.CharField(choices=[('ITEM_BASIC', 'Item basic amount'), ('ITEM_DISCOUNT', 'Item discount amount'), ('ITEM_AMOUNT', 'Item amount (after discount)'), ('TAX_AMOUNT', 'Tax amount'), ('ITEM_NET', 'Item net amount'), ('BILL_AMOUNT', 'Bill amount (running total)'), ('PREVIOUS_SUNDRY', 'Previous bill sundry')], default='ITEM_BASIC', max_length=20)),
                ('posting_account_purchase', models.ForeignKey(blank=True, help_text='Ledger posted when this sundry appears on a Purchase voucher.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_sundries_purchase', to='masters.account')),
                ('posting_account_sale', models.ForeignKey(blank=True, help_text='Ledger posted when this sundry appears on a Sale voucher.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_sundries_sale', to='masters.account')),
            ],
            options={
                'verbose_name': 'Bill Sundry',
                'verbose_name_plural': 'Bill Sundries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('narration', models.TextField(blank=True)),
                ('account', models.ForeignKey(help_text='Party or expense ledger (debited).', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='masters.account')),
                ('through', models.ForeignKey(help_text='Cash or bank ledger (credited).', on_delete=django.db.models.deletion.PROTECT, related_name='payments_through', to='masters.account')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=50)),
                ('narration', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='masters.account')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseBillSundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Leave 0 to auto-calculate from bill sundry formula.', max_digits=15)),
                ('bill_sundry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.billsundry')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_sundries', to='masters.purchase')),
            ],
            options={
                'verbose_name': 'Purchase Bill Sundry',
                'verbose_name_plural': 'Purchase Bill Sundries',
            },
        ),
        migrations.CreateModel(
            name='PurchaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tax_split_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Percent of item tax posted to Tax Account. Rest goes to Tax Account 2.', max_digits=5)),
                ('affect_stock', models.BooleanField(default=True)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('purchase_account', models.ForeignKey(help_text='Ledger debited for purchases (usually under Purchase).', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_types', to='masters.account')),
                ('tax_account', models.ForeignKey(blank=True, help_text='First tax ledger (CGST for local, IGST for interstate).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_type_tax', to='masters.account')),
                ('tax_account_2', models.ForeignKey(blank=True, help_text='Second tax ledger for local tax (SGST). Leave blank for IGST.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_type_tax_2', to='masters.account')),
            ],
            options={
                'verbose_name': 'Purchase Type',
                'verbose_name_plural': 'Purchase Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='masters.purchasetype'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('narration', models.TextField(blank=True)),
                ('account', models.ForeignKey(help_text='Party or income ledger (credited).', on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='masters.account')),
                ('through', models.ForeignKey(help_text='Cash or bank ledger (debited).', on_delete=django.db.models.deletion.PROTECT, related_name='receipts_through', to='masters.account')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=50)),
                ('narration', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='masters.account')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleBillSundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Leave 0 to auto-calculate from bill sundry formula.', max_digits=15)),
                ('bill_sundry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.billsundry')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_sundries', to='masters.sale')),
            ],
            options={
                'verbose_name': 'Sale Bill Sundry',
                'verbose_name_plural': 'Sale Bill Sundries',
            },
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tax_split_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Percent of item tax posted to Tax Account. Rest goes to Tax Account 2.', max_digits=5)),
                ('affect_stock', models.BooleanField(default=True)),
                ('tax_inclusive', models.BooleanField(default=False)),
                ('sales_account', models.ForeignKey(help_text='Ledger credited for sales (usually under Sale).', on_delete=django.db.models.deletion.PROTECT, related_name='sale_types', to='masters.account')),
                ('tax_account', models.ForeignKey(blank=True, help_text='First tax ledger (CGST for local, IGST for interstate).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_type_tax', to='masters.account')),
                ('tax_account_2', models.ForeignKey(blank=True, help_text='Second tax ledger for local tax (SGST). Leave blank for IGST.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_type_tax_2', to='masters.account')),
            ],
            options={
                'verbose_name': 'Sale Type',
                'verbose_name_plural': 'Sale Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='masters.saletype'),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='masters.item')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.sale')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='masters.unit')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='masters.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.purchase')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='masters.unit')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='alt_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_alt', to='masters.unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='main_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_main', to='masters.unit'),
        ),
    ]
