# Generated by Django 6.1 on 2026-09-09 03:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('GOODS', 'Goods'), ('SERVICE', 'Service')], default='GOODS', help_text='Goods: physical product with stock tracking. Service: no stock or unit required.', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_account',
            field=models.ForeignKey(blank=True, help_text='Purchase ledger for this item. Leave blank to use voucher-level default.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_purchase', to='masters.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_account',
            field=models.ForeignKey(blank=True, help_text='Sales ledger for this item. Leave blank to use voucher-level default.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_sale', to='masters.account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='alt_unit',
            field=models.ForeignKey(blank=True, help_text='Optional alternate unit (Goods only).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_alt', to='masters.unit'),
        ),
        migrations.AlterField(
            model_name='item',
            name='hsn',
            field=models.CharField(blank=True, help_text='HSN / SAC code, digits only (4, 6 or 8 digits).', max_length=8, validators=[django.core.validators.RegexValidator('^\\d*$', 'HSN must contain digits only.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='main_unit',
            field=models.ForeignKey(blank=True, help_text='Required for Goods. Leave blank for Services.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_main', to='masters.unit'),
        ),
    ]
