# Generated by Django 6.1 on 2026-09-04 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_registered',
            field=models.BooleanField(default=False, help_text='Tick if this party is GST registered.', verbose_name='Registered'),
        ),
        migrations.AddField(
            model_name='item',
            name='hsn',
            field=models.CharField(blank=True, help_text='HSN code, digits only (4, 6 or 8 digits).', max_length=8, validators=[django.core.validators.RegexValidator('^\\d*$', 'HSN must contain digits only.')]),
        ),
    ]
