# Generated by Django 5.2.17 on 2026-09-10 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_item_type_and_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='no_quantity',
            field=models.BooleanField(default=False, help_text="Mark this unit as 'N/A'. Items using it (goods or services) are billed with a quantity/rate as usual, but are never tracked as stock and never appear in the stock/valuation reports.", verbose_name='N/A (No Quantity)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='main_unit',
            field=models.ForeignKey(blank=True, help_text="Required for Goods (use the 'N/A' unit for goods you don't want stock-tracked). Optional for Services — pick a real unit like Hours/Job for billing, or leave blank / choose 'N/A' if quantity doesn't apply.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_main', to='masters.unit'),
        ),
    ]
