# Generated by Django 6.1 on 2026-08-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_payment_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='description',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
