# Generated by Django 5.2.17 on 2026-09-11 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_unit_no_quantity_alter_item_main_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetype',
            name='purchase_return_account',
            field=models.ForeignKey(blank=True, help_text='Ledger for Purchase Returns / Debit Notes against this purchase type. Leave blank to reuse the Purchase Account above.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_types_return', to='masters.account'),
        ),
        migrations.AddField(
            model_name='saletype',
            name='sales_return_account',
            field=models.ForeignKey(blank=True, help_text='Ledger for Sale Returns / Credit Notes against this sale type. Leave blank to reuse the Sales Account above.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_types_return', to='masters.account'),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.CharField(blank=True, max_length=50)),
                ('narration', models.TextField(blank=True)),
                ('account', models.ForeignKey(help_text='Customer / party account being credited (reduces what they owe you).', on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='masters.account')),
                ('against_sale', models.ForeignKey(blank=True, help_text='Optional: the original invoice this note relates to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='masters.sale')),
            ],
            options={
                'verbose_name': 'Credit Note',
                'verbose_name_plural': 'Credit Notes',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account', models.ForeignKey(help_text='Reason ledger debited by this note (e.g. Sales Return, Discount Allowed).', on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_lines', to='masters.account')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='masters.creditnote')),
            ],
            options={
                'verbose_name': 'Credit Note Line',
                'verbose_name_plural': 'Credit Note Lines',
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.CharField(blank=True, max_length=50)),
                ('narration', models.TextField(blank=True)),
                ('account', models.ForeignKey(help_text='Supplier / party account being debited (reduces what you owe them).', on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='masters.account')),
                ('against_purchase', models.ForeignKey(blank=True, help_text='Optional: the original invoice this note relates to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes', to='masters.purchase')),
            ],
            options={
                'verbose_name': 'Debit Note',
                'verbose_name_plural': 'Debit Notes',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DebitNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account', models.ForeignKey(help_text='Reason ledger credited by this note (e.g. Purchase Return, Discount Received).', on_delete=django.db.models.deletion.PROTECT, related_name='debit_note_lines', to='masters.account')),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='masters.debitnote')),
            ],
            options={
                'verbose_name': 'Debit Note Line',
                'verbose_name_plural': 'Debit Note Lines',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.CharField(blank=True, max_length=50)),
                ('narration', models.TextField(blank=True)),
                ('account', models.ForeignKey(help_text='Supplier account (debited).', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='masters.account')),
                ('against_purchase', models.ForeignKey(blank=True, help_text='Optional: the original invoice this return is against.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='masters.purchase')),
                ('purchase_type', models.ForeignKey(blank=True, help_text='Reused from Purchase Types. Determines the Purchase Return and tax ledgers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='masters.purchasetype')),
            ],
            options={
                'verbose_name': 'Purchase Return',
                'verbose_name_plural': 'Purchase Returns',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnBillSundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Leave 0 to auto-calculate from bill sundry formula.', max_digits=15)),
                ('bill_sundry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.billsundry')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_sundries', to='masters.purchasereturn')),
            ],
            options={
                'verbose_name': 'Purchase Return Bill Sundry',
                'verbose_name_plural': 'Purchase Return Bill Sundries',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='masters.item')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.purchasereturn')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='masters.unit')),
            ],
            options={
                'verbose_name': 'Purchase Return Item',
                'verbose_name_plural': 'Purchase Return Items',
            },
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_no', models.CharField(blank=True, max_length=50)),
                ('narration', models.TextField(blank=True)),
                ('account', models.ForeignKey(help_text='Customer account (credited).', on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to='masters.account')),
                ('against_sale', models.ForeignKey(blank=True, help_text='Optional: the original invoice this return is against.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='masters.sale')),
                ('sale_type', models.ForeignKey(blank=True, help_text='Reused from Sale Types. Determines the Sales Return and tax ledgers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_returns', to='masters.saletype')),
            ],
            options={
                'verbose_name': 'Sale Return',
                'verbose_name_plural': 'Sale Returns',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnBillSundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Leave 0 to auto-calculate from bill sundry formula.', max_digits=15)),
                ('bill_sundry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.billsundry')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_sundries', to='masters.salereturn')),
            ],
            options={
                'verbose_name': 'Sale Return Bill Sundry',
                'verbose_name_plural': 'Sale Return Bill Sundries',
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_return_items', to='masters.item')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.salereturn')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_return_items', to='masters.unit')),
            ],
            options={
                'verbose_name': 'Sale Return Item',
                'verbose_name_plural': 'Sale Return Items',
            },
        ),
    ]
