# Generated by Django 5.2.17 on 2026-09-12 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_purchasetype_purchase_return_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('trade_name', models.CharField(blank=True, max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$', 'Enter a valid 15-character GSTIN (e.g. 27ABCDE1234F1Z5).')], verbose_name='GSTIN')),
                ('state', models.CharField(blank=True, choices=[('Jammu and Kashmir', 'Jammu and Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Punjab', 'Punjab'), ('Chandigarh', 'Chandigarh'), ('Uttarakhand', 'Uttarakhand'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('Rajasthan', 'Rajasthan'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Bihar', 'Bihar'), ('Sikkim', 'Sikkim'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Nagaland', 'Nagaland'), ('Manipur', 'Manipur'), ('Mizoram', 'Mizoram'), ('Tripura', 'Tripura'), ('Meghalaya', 'Meghalaya'), ('Assam', 'Assam'), ('West Bengal', 'West Bengal'), ('Jharkhand', 'Jharkhand'), ('Odisha', 'Odisha'), ('Chhattisgarh', 'Chhattisgarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Gujarat', 'Gujarat'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Maharashtra', 'Maharashtra'), ('Andhra Pradesh (Old)', 'Andhra Pradesh (Old)'), ('Karnataka', 'Karnataka'), ('Goa', 'Goa'), ('Lakshadweep', 'Lakshadweep'), ('Kerala', 'Kerala'), ('Tamil Nadu', 'Tamil Nadu'), ('Puducherry', 'Puducherry'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Ladakh', 'Ladakh'), ('Other Territory', 'Other Territory')], max_length=50)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='gst',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$', 'Enter a valid 15-character GSTIN (e.g. 27ABCDE1234F1Z5).')], verbose_name='GSTIN'),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(blank=True, choices=[('Jammu and Kashmir', 'Jammu and Kashmir'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Punjab', 'Punjab'), ('Chandigarh', 'Chandigarh'), ('Uttarakhand', 'Uttarakhand'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('Rajasthan', 'Rajasthan'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Bihar', 'Bihar'), ('Sikkim', 'Sikkim'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Nagaland', 'Nagaland'), ('Manipur', 'Manipur'), ('Mizoram', 'Mizoram'), ('Tripura', 'Tripura'), ('Meghalaya', 'Meghalaya'), ('Assam', 'Assam'), ('West Bengal', 'West Bengal'), ('Jharkhand', 'Jharkhand'), ('Odisha', 'Odisha'), ('Chhattisgarh', 'Chhattisgarh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Gujarat', 'Gujarat'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Maharashtra', 'Maharashtra'), ('Andhra Pradesh (Old)', 'Andhra Pradesh (Old)'), ('Karnataka', 'Karnataka'), ('Goa', 'Goa'), ('Lakshadweep', 'Lakshadweep'), ('Kerala', 'Kerala'), ('Tamil Nadu', 'Tamil Nadu'), ('Puducherry', 'Puducherry'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Telangana', 'Telangana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Ladakh', 'Ladakh'), ('Other Territory', 'Other Territory')], max_length=50),
        ),
    ]
