# Generated by Django 5.2.17 on 2026-09-14 08:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_companyprofile_alter_account_gst_alter_account_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST Compensation Cess %, if applicable (tobacco, luxury cars, aerated drinks, etc). Leave 0 if not applicable.', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_reverse_charge',
            field=models.BooleanField(default=False, help_text="Tick if GST on this purchase is payable by you under Reverse Charge (e.g. unregistered supplier, notified goods/services). The supplier is then credited only the taxable value; the GST is self-assessed as both an input credit and a payable liability. Requires the Purchase Type's 'RCM payable account' to be set.", verbose_name='Reverse Charge applicable (RCM)'),
        ),
        migrations.AddField(
            model_name='purchasetype',
            name='is_interstate',
            field=models.BooleanField(default=False, help_text="Tick for Interstate Purchase Types (posts IGST). Leave unticked for Local (posts CGST+SGST). Used to auto-suggest a Purchase Type when the party's state differs from your Company Profile state."),
        ),
        migrations.AddField(
            model_name='purchasetype',
            name='rcm_payable_account',
            field=models.ForeignKey(blank=True, help_text="GST Payable (Reverse Charge) liability ledger. Required only for purchases marked 'Reverse Charge applicable'. Leave blank if you never use RCM.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_types_rcm', to='masters.account'),
        ),
        migrations.AddField(
            model_name='saletype',
            name='is_interstate',
            field=models.BooleanField(default=False, help_text="Tick for Interstate Sale Types (posts IGST). Leave unticked for Local (posts CGST+SGST). Used to auto-suggest a Sale Type when the party's state differs from your Company Profile state."),
        ),
        migrations.AlterField(
            model_name='item',
            name='hsn',
            field=models.CharField(blank=True, help_text='HSN / SAC code, digits only (4, 6 or 8 digits).', max_length=8, validators=[django.core.validators.RegexValidator('^(\\d{4}|\\d{6}|\\d{8})$', 'HSN/SAC must be 4, 6, or 8 digits.')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST rate %. Standard slabs: 0, 0.25, 3, 5, 12, 18, 28.', max_digits=5),
        ),
    ]
