# Generated by Django 5.2.17 on 2026-09-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_item_cess_rate_purchase_is_reverse_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='free_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Extra quantity given free with this line (e.g. a '10+2' scheme: enter 10 in Quantity and 2 here). Free quantity moves stock in/out like the billed quantity, but is never billed or taxed — it plays no part in Basic Amount or any amount calculated from it.", max_digits=15),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='free_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Extra quantity given free with this line (e.g. a '10+2' scheme: enter 10 in Quantity and 2 here). Free quantity moves stock in/out like the billed quantity, but is never billed or taxed — it plays no part in Basic Amount or any amount calculated from it.", max_digits=15),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='free_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Extra quantity given free with this line (e.g. a '10+2' scheme: enter 10 in Quantity and 2 here). Free quantity moves stock in/out like the billed quantity, but is never billed or taxed — it plays no part in Basic Amount or any amount calculated from it.", max_digits=15),
        ),
        migrations.AddField(
            model_name='salereturnitem',
            name='free_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Extra quantity given free with this line (e.g. a '10+2' scheme: enter 10 in Quantity and 2 here). Free quantity moves stock in/out like the billed quantity, but is never billed or taxed — it plays no part in Basic Amount or any amount calculated from it.", max_digits=15),
        ),
    ]
